# Generated by Django 5.0.6 on 2024-07-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
