# Generated by Django 5.0.6 on 2024-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_app', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'api_pwndb_db_mails',
            },
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'api_pwndb_mails',
            },
        ),
        migrations.CreateModel(
            name='MailsDbMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mails', models.IntegerField(unique=True)),
                ('id_db_mails', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'api_pwndb_mails_db_mails',
            },
        ),
    ]
