# Generated by Django 5.0.4 on 2024-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pa_app", "0003_dbmails_mails_mailsdbmails"),
    ]

    operations = [
        migrations.AddField(
            model_name="mails",
            name="source",
            field=models.CharField(default="Inconnue", max_length=255),
        ),
    ]
